import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { AuthProvider } from "@/components/providers/AuthProvider"
import { RouteGuard } from "@/components/providers/RouteGuard"
import { Toaster } from "@/components/ui/sonner"
import QueryProvider from "@/components/providers/QueryProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TaluiThai",
  description: "Generated by TaluiThai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AuthProvider>
            <RouteGuard>
              <SidebarProvider>
                <AppSidebar />
                <main className="w-full relative overflow-x-hidden">
                  {children}
                </main>
                <Toaster position="top-right" />
              </SidebarProvider>
            </RouteGuard>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

